### ISSUE TITLE
Re-introduce ORM samples with dummy database plugin

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura-Sample#110]
#109 removed the ORM examples from Kitura-Sample as it otherwise requires users to install Postgres dependencies.

However, Kitura-Sample could include ORM and Kuery samples that work out-of-the-box, by using a 'dummy' database plugin (something that is backed by a simple in-memory structure for example).

I believe such a thing is [already implemented in the Kuery tests](https://github.com/IBM-Swift/Swift-Kuery/blob/2.0.0/Tests/SwiftKueryTests/CommonUtils.swift).  Could we use this as the basis of something simple that would provide enough functionality for the purposes of the sample?

**Comment by Andrew-Lees11** [comment]
Closing now the [pr](https://github.com/IBM-Swift/Kitura-Sample/pull/121) which adds this functionality has been merged.
