### ISSUE TITLE
can't compile with recommended Swift version for Kitura

### ISSUE THREAD

**Issue by rshev** [IBM-Swift/Kitura-Sample#16]
Hey there! After being to Swift London trying to start with Kitura (have a simple task to make a kind-of smart backend mockup for an app) but stuck even compiling this sample.

I've installed the recommended by main Kitura repo swift DEVELOPMENT-SNAPSHOT-2016-05-09.
And have a couple of errors during compilation of this project (seems that SwiftyJSON is the problem):

```
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:124:14: error: cannot invoke 'JSON.init' with an argument list of type '([AnyObject])'
        self.init(jsonArray.map { $0.object })
             ^
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:124:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
        self.init(jsonArray.map { $0.object })
             ^
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:143:14: error: cannot invoke 'JSON.init' with an argument list of type '([String : AnyObject])'
        self.init(dictionary)
             ^
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:143:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
        self.init(dictionary)
             ^
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:296:29: error: return expression of type '[AnyObject]' does not conform to 'AnyObject'
                return self.rawArray
                       ~~~~~^~~~~~~~
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:298:29: error: return expression of type '[String : AnyObject]' does not conform to 'AnyObject'
                return self.rawDictionary
                       ~~~~~^~~~~~~~~~~~~
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:300:29: error: return expression of type 'String' does not conform to 'AnyObject'
                return self.rawString
                       ~~~~~^~~~~~~~~
/Users/asdfgh1/tmp/Kitura-Sample/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:332:94: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
                _error = NSError(domain: ErrorDomain, code: ErrorUnsupportedType, userInfo: [NSLocalizedDescriptionKey: "It is a unsupported type"])
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by shmuelk** [comment]
@rshev. Actually the recommended version of Swift for 0.16.x of Kitura is 05/03 as is stated in the 0.16.X version of the README.md. You were running 05/09. That version of Swift is supported by the 0.17.x version of Kitura.

**Comment by shmuelk** [comment]
@rshev Also if you cloned Kitura-Sample, you want to clone the version in the develop branch. That version supports Kitura 0.17.x.

**Comment by rshev** [comment]
@shmuelk thanks for clarification, it worked from the develop branch. Readmes are kind of confusing for beginners, because https://github.com/IBM-Swift/Kitura suggests `DEVELOPMENT-SNAPSHOT-2016-05-09` and Readme here doesn't suggest any particular version. Just a hint :)

**Comment by beset** [comment]
Hi ~
The recommend version now is DEVELOPMENT-SNAPSHOT-2016-06-06, and i'm on the develop branch but i still some error while compiling 'Kitura':
`Compile Swift Module 'Kitura' (34 sources)
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/MimeTypeAcceptor.swift:112:17: error: closure cannot implicitly capture an inout parameter unless @noescape
                criteriaMatches[type] = (priority: priority, qValue: parsedHeaderValue.qValue)
                ^
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/Router.swift:112:14: warning: result of call to 'all(_:middleware:)' is unused
        self.all(route, middleware: subrouter)
             ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/Router.swift:279:26: warning: result of call to 'send(fileName:)' is unused
            try response.send(fileName: resourceFileName)
                         ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/staticFileServer/FileServer.swift:105:17: warning: result of call to 'serveIfNonDirectoryFile(atPath:response:)' is unused
                serveIfNonDirectoryFile(atPath: filePathWithExtension, response: response)
                ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/staticFileServer/FileServer.swift:114:38: warning: result of call to 'redirect' is unused
                        try response.redirect(requestPath + "/")
                                     ^       ~~~~~~~~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/staticFileServer/FileServer.swift:146:30: warning: result of call to 'send(fileName:)' is unused
                try response.send(fileName: filePath)
                             ^   ~~~~~~~~~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:176:9: warning: result of call to 'send' is unused
        send(str)
        ^   ~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:191:9: warning: result of call to 'send(data:)' is unused
        send(data: data)
        ^   ~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:206:13: warning: result of call to 'send(data:)' is unused
            send(data: data)
            ^   ~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:245:9: warning: result of call to 'send(data:)' is unused
        send(data: data)
        ^   ~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:261:9: warning: result of call to 'send' is unused
        send(jsonStr)
        ^   ~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:287:14: warning: result of call to 'status' is unused
        self.status(status)
             ^     ~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:289:13: warning: result of call to 'send' is unused
            send(statusCode)
            ^   ~~~~~~~~~~~~
/Users/isan/Kitura-Sample/Packages/Kitura-0.17.8/Sources/Kitura/RouterResponse.swift:401:13: warning: result of call to 'send(fileName:)' is unused
        try send(fileName: download)
            ^   ~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-06-06-a.xctoolchain/usr/bin/swift-build-tool -f /Users/isan/Kitura-Sample/.build/debug.yaml
make: *** [build] Error 1`

**Comment by ianpartridge** [comment]
Closing this as the original issue is fixed, and there's another issue for the follow on problem.
