### ISSUE TITLE
Add directions to README for building and running in XCode.

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura-Sample#19]

**Comment by dfirsht** [comment]
We already have a wiki entry on this: https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-on-XCode. Would it be sufficient to just add a link to this, or leave it how it is? @kweinmeister @shmuelk thoughts?

**Comment by shmuelk** [comment]
@dfirsht I think we should add a link to the wiki. However, I think we need to review all of the Wiki entries. Many important ones are very out of data.
