### ISSUE TITLE
Sample project works from the command line, doesn't compile from Xcode (CCurl missing)

### ISSUE THREAD

**Issue by greg3z** [IBM-Swift/Kitura-Sample#27]
I followed the steps on the Kitura & Kitura-Sample pages and manage to get the server running from the command line, but it doesn't compile from Xcode. The error is: 'No such module CCurl'.

I'm running Xcode 8b6 with the 25-07 snapshot.

**Comment by vadimeisenbergibm** [comment]
@greg3z Please try running `make openXcode` in the command line. It will generate Xcode project and open it for you.

Alternatively, please see https://github.com/IBM-Swift/Kitura/wiki/Building-your-Kitura-application-in-Xcode#troubleshooting

**Comment by greg3z** [comment]
Hello Vadim and thank you for your quick answer!

The make openXcode command works as intended but once in Xcode, I still get the  'No such module CCurl' error, even after modifying the Library Search Path as recommended in your link.

**Comment by vadimeisenbergibm** [comment]
You are welcome, Greg. Do you have curl command on your Mac? If not, please try `brew install curl`.

**Comment by greg3z** [comment]
Yes, curl is installed, here is the version I have:
`curl 7.50.0 (x86_64-apple-darwin15.5.0) libcurl/7.50.0 SecureTransport zlib/1.2.5`

**Comment by vadimeisenbergibm** [comment]
OK, let somebody from the Kitura core team handle it.

**Comment by Lascorbe** [comment]
Any updates on this? I'm having the same issue.

**Comment by shmuelk** [comment]
I'm running XCode 8 GA, the Toolchain is set to the default one. Kitura-Sample builds, but won't run. We need to investigate this some more.

**Comment by rob-deans** [comment]
Hi @greg3z, @Lascorbe  are you still having the problem? I have managed to build and run Kitura-Sample on XCode 8.0 again with the default toolchain.

**Comment by greg3z** [comment]
Hello @rob-deans, I'll check that tonite as I don't have my mbp with me.

**Comment by greg3z** [comment]
No, sadly, with the last Xcode (8A218a) and the default toolchain, I get the same error.

**Comment by rob-deans** [comment]
@greg3z could you show us your search path inside `Build Settings` under `KituraSample`, it should look something like this:
![screen shot 2016-09-28 at 12 04 48](https://cloud.githubusercontent.com/assets/17593196/18911267/fea6abfa-8573-11e6-9656-e1561b5fcced.png)

**Comment by greg3z** [comment]
I have those 4 (the 1st is twice in the list):
/Users/glhotellier/Library/Mobile (this isn't a valid path btw, probably the beginning of Mobile Documents...)
Documents/com~apple~CloudDocs/code/Kitura-Sample/Packages/CCurl-0.2.1
Documents/com~apple~CloudDocs/code/Kitura-Sample/Packages/CHTTPParser-0.3.0/Sources/CHTTPParser/include

All those path are configured as non-recursive

**Comment by youming-lin** [comment]
@greg3z Someone else encountered a similar problem before and was able to solve the issue, presumably by removing spaces from path.
https://gitter.im/IBM-Swift/Kitura?at=57dab85bc3e7045a3050b2ee

**Comment by greg3z** [comment]
Thank you @youming-lin!

Indeed, it was because of a space in the path where I installed the project. I tried installing it on a path with no spaces and it worked!
