### ISSUE TITLE
KituraSample stopped after running for some Tens of minutes 

### ISSUE THREAD

**Issue by swiftc-org** [IBM-Swift/Kitura-Sample#3]
I run KituraSample by using nohup ./KituraSample &
then I close the ssh connection, I can access to the web server on the Tens of minutes, But after this It failed. Who can help me?
BTW: I also tried the way of screen

**Comment by kweinmeister** [comment]
Is the error still reproducible on the 4/25 Swift snapshot using the `develop` branch? If so, can you please let us know the detailed reproduction steps, and what error you are seeing?

**Comment by dfirsht** [comment]
My guess is that this had to do with memory leak issues: https://github.com/IBM-Swift/Kitura/issues/419. Since these are being fixed I'm going to close this issue. If this still occurs we can reopen this issue or open a new one.
