### ISSUE TITLE
Accessing /error segfaults the demo app

### ISSUE THREAD

**Issue by sgharms** [IBM-Swift/Kitura-Sample#33]
Running the sample app:

```text
Swift version 3.0-dev (LLVM f54fa77021, Clang 0e6c928036, Swift e9d457540a)
Target: x86_64-unknown-linux-gnu
```

Visit: `/error`

Result: Server dies

Output:

```text
ERROR: KituraSample main.swift line 88 - Example of error being set
[1]    12344 segmentation fault (core dumped)  ./.build/debug/KituraSample
```

I've spent 20 minutes with the framework at this point, but I don't think dropping core is the right behavior based on the `main.swift` file.

**Comment by irar2** [comment]
@sgharms could you please verify that the problem was solved?

**Comment by sgharms** [comment]
Issue closable. The issue was that the development releases after the 3.0 production release had this behavior. Reverting to 3.0 was successful.  BU wary all adventures who would step here.

**Comment by shmuelk** [comment]
@irar2 Recreated the problem on Swift 3.0 production release. Thus the fix.
