### ISSUE TITLE
Update readme to tell user to not use the Download Zip from Github. Instead clone repo

### ISSUE THREAD

**Issue by csantanapr** [IBM-Swift/Kitura-Sample#4]
Update readme to tell user to not use the Download Zip from Github. To instead clone the repo since the `make run` command assumes it's a git repo to download submodules

`git clone --depth=1 https://github.com/IBM-Swift/Kitura-Sample.git`

Steps to recreate 
1. Click Download Zip from Github Repo
2. Unzip and open terminal
3. Run make run
```
~/Downloads
⛄  $ cd Kitura-Sample-master
~/Downloads/Kitura-Sample-master
⛄  $ make run
--- Fetching Kitura-Build submodule
git submodule init
fatal: Not a git repository (or any of the parent directories): .git
make: *** No rule to make target `build', needed by `run'.  Stop.
```

**Comment by ianpartridge** [comment]
Thanks for reporting this.  I've updated `README.md` in [this commit](https://github.com/IBM-Swift/Kitura-Sample/commit/dad8d5bb2591ad826b50801539a1bd1542e9223f).
