### ISSUE TITLE
No such file or directory [run] Error 1

### ISSUE THREAD

**Issue by TomasSergeant** [IBM-Swift/Kitura-Sample#41]
When I try to run the project I get the following error.

running on macOS Sierra 10.12

$ make run
make SWIFT_BUILD_CONFIGURATION="debug" SWIFTC_FLAGS="-Xswiftc -DDEBUG" _build
--- Running build on Darwin
--- Build scripts directory: Package-Builder/build
--- Checking swift version
swift --version
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9
--- Checking swiftc version
swiftc --version
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9
--- Checking git version
git --version
git version 2.8.4 (Apple Git-73)
--- Checking git revision and branch
git rev-parse HEAD
710bc7b39711efe1f2bf1130a19962bc1d79eaa6
git rev-parse --abbrev-ref HEAD
master
--- Invoking swift build
swift build -c debug -Xswiftc -DDEBUG  
Compile Swift Module 'Spectre' (8 sources)
Compile Swift Module 'Bridging' (4 sources)
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'SwiftyJSON' (2 sources)
Compile Swift Module 'Socket' (3 sources)
Compile Swift Module 'LoggerAPI' (1 sources)
Compile Swift Module 'HeliumLogger' (1 sources)
Compile Swift Module 'PathKit' (1 sources)
Compile Swift Module 'SSLService' (1 sources)
Compile Swift Module 'Stencil' (15 sources)
Compile Swift Module 'KituraNet' (29 sources)
Compile Swift Module 'KituraStencil' (1 sources)
Compile Swift Module 'Mustache' (32 sources)
Compile Swift Module 'Kitura' (40 sources)
Compile Swift Module 'KituraMustache' (1 sources)
Compile Swift Module 'Kitura_Sample' (1 sources)
Linking ./.build/debug/Kitura-Sample
--- Invoking KituraSample executable
./.build/debug/KituraSample
make: ./.build/debug/KituraSample: No such file or directory
make: *** [run] Error 1

**Comment by vadimeisenbergibm** [comment]
@TomasSergeant I have fixed the issue in commit https://github.com/IBM-Swift/Kitura-Sample/commit/ac2f2528125b94d5833bbc2e748ad652c329dabc
