### ISSUE TITLE
ld: library not found for -lCHTTPParser for architecture x86_64

### ISSUE THREAD

**Issue by lizixroy** [IBM-Swift/Kitura-Sample#51]
Got this error when building in Xcode on OS X El Capitan 10.11.6 (15G31):
```
ld: library not found for -lCHTTPParser for architecture x86_64 #51
```

Any idea how to resolve this issue?

Thanks.

**Comment by ianpartridge** [comment]
Which version of Xcode?

**Comment by lizixroy** [comment]
@ianpartridge Version 8.0 (8A218a)

**Comment by shmuelk** [comment]
What was in the Package.swift file that you used to generate the Xcode project? 

I assume you were using the Swift toolchain that came with Xcode and that when you migrated from Xcode 8.0 to Xcode 8.1 you regenerated the Xcode project.

**Comment by lizixroy** [comment]
@ianpartridge @shmuelk Thanks for the help, I solved the problem by adding "$SRCROOT/.build/debug" to the Library Search Path in Kitura target. It now compiles fine.

This was suggested by someone in the Kitura Slack channel, I don't know why it works though.
