### ISSUE TITLE
library not found for -lCHTTPParser for architecture x86_64

### ISSUE THREAD

**Issue by gauravmb** [IBM-Swift/Kitura-Sample#62]
I am not able to compile, as i am facing below issue 

![screen shot 2017-01-09 at 5 54 46 pm](https://cloud.githubusercontent.com/assets/3609182/21766532/14ec6504-d695-11e6-9cb8-9363eecaac28.png)

I tried with different architecture, but no help, Also i have googled on the same, but didnt found any working solution.

**Comment by shmuelk** [comment]
Can you please try again, after having done the following:
```bash
rm -rf Packages
swift package generate-xcodeproj
```

I would also try deleting the derived data in XCode as well as doing a Clean (Alt Shift-K) before building again).

**Comment by gauravmb** [comment]
Followed the same as above, but still facing the same issue.
