### ISSUE TITLE
library not found for -lCHTTPParser for architecture x86_64

### ISSUE THREAD

**Issue by gauravmb** [IBM-Swift/Kitura-Sample#63]
![screen shot 2017-01-09 at 5 54 46 pm](https://cloud.githubusercontent.com/assets/3609182/21840556/25ce4c82-d804-11e6-804e-6e900f3eb42d.png)

**Comment by gauravmb** [comment]
We have already tried the below

rm -rf Packages
swift package generate-xcodeproj

**Comment by shmuelk** [comment]
Have you deleted the DerivedData for the project and rebuilt?

Please post here the list of directories in the Packages directory of your project.

Also check the list of Products, your project is generating and check that there is a CHTTPParser product and its location.
